### ISSUE TITLE
Future Plans and TODOs

### ISSUE THREAD

**Issue by digikar99** [marcoheisig/sb-simd#3]
Hi! Thanks for the work!

I ended up working on something similar as part of [numericals](https://github.com/digikar99/numericals/tree/master/sbcl) and felt I should divide numericals into multiple pieces - one piece would be concerned with SIMD operations with SBCL, for which I might start with this library.

I do feel a need for renaming - f32 and f64 to float32 and float64, uX to uintX, sX to intX just to keep things consistent with other languages and keep unfamiliarity for new people to a minimum; but I might just as well define these wrapper types in the higher library, and keep the naming conventions as they are, since they do save a small bit of horizontal space.

One confirmation I wanted was using an alternative to reader conditionals, since `:sb-simd-pack(-256)` are no longer in `*features*`; so I am using a `(macro-when (member :sb-simd-pack(-256) sb-impl::*features*) ...)`. Let me know if I'm missing something in this regard, or would this be the way to go.

```lisp
(defmacro macro-when (condition &body body)
  (when condition `(progn ,@body)))
```

Other than that, if you find the time, I'd want to hear your opinion on the TODOs, some I can think of include:

- including pack support for uX and sX for X in {1,2,4,8,16,32} - I wanted to know if this is an SBCL thing, but looking at the code for `sb-vm::%make-simd-pack-256-ub32`, it does seem very doable
- arithmetic operations on integers of all varieties
- some more simd intrinsic functions, sqrt, reciprocals
- more complex functions, eg. transcendental functions

... anything else you can think of ...

**Comment by marcoheisig** [comment]
Hello @digikar99!  It is great to hear you are interested in this library.

The code is in a very half-finished state (even for a Lisp project), so I feel free to use/rename/redesign parts of it any way you like.

I haven't found any time to work on this further, because teaching and my work on Petalisp take up most of my time.  But things are starting to look solid in Petalisp, so I could imagine to work further on sb-simd during winter.  That means we could even collaborate on some of the tasks.  If so, I could add you as a contributor, and maybe we could discuss things on my Jitsi server.  How does that sound?

Let me conclude by discussing your TODOs:

- The trouble with SIMD packs for certain integer types is that they are not properly type-tagged in SBCL as of now.  Internally, there are only three different SIMD element type tags - integer, single and double.  So I am all in for new packing and unpacking functions, but don't expect to be able to write a generic SIMD-PACK-VALUES function.  By the way, this is also where I stopped working, because I wanted to submit some SBCL patches first, and I never found the time for that.

- I am all in for new integer operations.  The biggest question is whether one wants them to be 'smart', or close to the AVX2 instruction set.  I originally wanted smart operations (implicit coercion, ...), but it turned out that implementing them is a headache, even with macros.  That is why I think now that sb-simd should be focused on low-level functionality.

- Yes, more intrinsic functions are always good.

- Transcendental functions sound good, too.  We should just make sure that this project doesn't grow so far that it becomes a maintenance burden.  I don't think we have the manpower to write another Intel MKL.

One project that I'd definitely like to tackle is to implement proper X-AREF and X-ROW-MAJOR-AREF functions for all supported SIMD types X.

**Comment by digikar99** [comment]
Hmm, now that you mention Intel MKL, and I think I'm wanting this to be more than just a experiment, I think I just as might exhaustively survey the lisp ecosystem to compare the available numerical computing libraries - or has anyone already? The last I checked, SBCL's `exp` wraps around a foreign function resulting in speeds that are 3 times as slow as native. I'm not sure if that is also the case with other CFFI based libraries. An even more general problem would be speeding up CFFI itself.

About the TODOs, if after the survey I find that effort in this direction is worthwhile, with the points you mentioned, I think, things can be divided into at least two levels: a minimal core implementing native simd functions on fixnums and single and double floats; then an expansion spanning other integer types as also transcendental functions. About this last part, I also received some code from Bela Pecsek who has been enthusiastically playing with the computer language benchmarks game producing some as-of-yet-unmeasured-by-me optimizedsqrt and dot product functions. 

But that after the survey I think. For me, lisp is a great creativity outlet amidst college work, so I hope to continue with it atleast until `julia --lisp` becomes popular and/or julia itself stables down; I do possess a few complaints about julia, not sure if I'm nitpicking - the JIT Compilation thing and the lack of compile time warnings and notes like SBCL, non-lispy syntax that renders paredit useless, lack of dynamic scoping, and condition systems. 

I hope to get back to you after the survey then! Thanks for the pointer!

**Comment by digikar99** [comment]
... okay, a simple survey was quick; though, a few are left out

https://gist.github.com/digikar99/16066dbf24b8789c969ea58837e0fbef

The "Implementation" column needs to be improved; some libraries (like LLA) seem to use a hybrid approach of keeping the data in lisp, while invoking the blas/lapack function on the data without actually copying the data. Doing things natively - the role of `sb-simd` is important, since `numericals` did turn out to be the fastest; there's another macro `numericals:weop` that was taking  just 0.001 sec to do the addition.

And when the human effort would be insufficient to do things natively - the transcendental function - it's okay to call the foreign function. Yet to look into CFFI performance yet.

**Comment by digikar99** [comment]
You can add me to Jitsi. Do I need to do any setup?

sb-simd is promising. Just tested julia as well, simple in-place addition of 2 10000x10000 matrices, super-optimized SBCL (`numericals:weop` with `(safety 0)` and type-declarations) wins by about 25%. So, `@. c = a + b` vs `(numericals:weop c (+ a b))` with all of them preallocated.

EDIT: About the `aref` and `row-major-aref`, for SBCL, I'm seeing that `aref` is implemented in terms of `row-major-aref`. In addition, I am unable to see the semantics of `aref` for simd packs.

**Comment by marcoheisig** [comment]
I sent you an email about the Jitsi.

I am glad to see those benchmarks results :)

About the semantics of aref for simd packs:  I suggest having a separate `X-row-major-aref` and `X-aref` function for each kind of simd pack.  The supplied indices denote the position of the first of several consecutive entries that are loaded as one pack.  The non-`(safety 0)` version of these functions has to ensure that both the index and its successors are valid.  The `(safety 0)` version just emits a suitable unaligned SIMD load instruction.

I recommend sticking to unaligned loads everywhere.  There is no simple way to enforce alignment in Lisp, and on modern CPUs there is almost zero penalty for using unaligned loads instead of aligned loads.

**Comment by digikar99** [comment]
Yeah, `row-major-aref` seems semantically sensible, but `aref` for multidimensional arrays doesn't seem so much sematically sensible to me; `aref` does make sense for a single element in the case of multidimensional arrays; for more than one, it's, well, okay to have, but just doesn't seem to make sense.

Also, had that experience; tried to use the aligned using static-vectors and some tricks, didn't make a ton of speed difference; learnt about `vzeroupper` that becomes a deal breaker while mixing avx and sse code.

**Comment by bpecsek** [comment]
Dear Marco,

I have just started looking at your sb-simd code a few days ago.

I have added support for u64.2, u64.4, u32.4 and u32.8 and found a bug or two in the define-nary-wrapper* macro in wrapper.lisp.

How can I send this modifications to you to merge it with the master.

I would also like to send the fast vdot function based on avx2 fma and a few others that you could add that digicar99 has already mentioned. And also extend it further in my spare time if you don't mind.

I have though problem with the aref support. (f64.4-aref v 0) and row-major-aref seems to work (after I added the aref vops in sb-simd.ads) but the (setf (f64.4-aref v 0) (make-f64.4 1d0 2d0 3d0 4d0)) gives error 
"The function SB-SIMD::F64.4-HAIRY-DATA-VECTOR-SET is undefined.
   [Condition of type UNDEFINED-FUNCTION]" 

(setf (f64.4-row.major-aref v 0) (make-f64.4 1d0 2d0 3d0 4d0)) gives error 
"The value
  #<SB-EXT:SIMD-PACK-256 3FF0000000000000 4000000000000000 4008000000000000 4010000000000000>

is not of type
  DOUBLE-FLOAT
when setting an element of (ARRAY DOUBLE-FLOAT)
   [Condition of type TYPE-ERROR]"

How aref support is added seems to be a bit complicated.

How is it better from the one did by digikar99 in numericals?

**Comment by marcoheisig** [comment]
Hello @bpecsek,

thanks for your interest in this project.  Let me try to answer your questions:

> How can I send this modifications to you to merge it with the master.

Just send me pull requests.  If you behave well, I could also make you a contributor.

> I would also like to [...] extend it further in my spare time if you don't mind.

No, I don't mind at all.  I will also gladly review all your patches.

> aref support

I haven't really worked on aref support so far.  If anything, the current state is a demo.  Any yes, we might want to borrow some things from numericals.  But I haven't given that much thought so far.

I am currently very busy chairing the https://european-lisp-symposium.org/2021, but there is hope that I will have more time afterwards.  I really want to get things going in terms of SIMD support.

**Comment by marcoheisig** [comment]
OK, SIMD pack loads and stores (e.g., f64.4ref, row-major-f64.4ref) should work now, with bounds checking, inlining, and all the other bells and whistles.  Now I just have to clean up a few things, and this library is ready to be shipped.

**Comment by bpecsek** [comment]
Hi Marco,

I wish we had the signed integer types (at least the sb64 and sb32) as well.
I feel a bit down that no calculations can be done with negative integers.
The package feels incomplete without the signed integer types.
Even unsigned bytes are not fully functional without the signed ones.

On the other hand, I fully agree that single and double floats are way more important in most domains and it is better to have a meal 4/5th cooked than going hungry.

Regards,
Bela
